# Generated by Django 3.1.4 on 2021-02-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210213_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0, verbose_name='rating'),
        ),
    ]
